language: python
python:
  - "3.5.2"

services:
  - postgresql

sudo: required
install:

  make install
  make install-requirements
  # - pip install pyTelegramBotAPI
  # - pip install -U pytest
  # -


script: make test
