language: python
python:
  - "3.5.2"

services:
  - postgresql

sudo: required
install:

  - python setup.py install
  - sudo pip install --upgrade pip
  - pip install -r requirements.txt

  # - pip install pyTelegramBotAPI
  # - pip install -U pytest
  # -


script: make test
